#! /bin/bash
#
# Defaults to 3 levels deep, do more with `t 5` or `t 1`
# pass additional args after

tree -I '.git|node_modules|bower_components|.DS_Store' --dirsfirst --filelimit 15 -L ${1:-3} -aC $2
