# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export DOTFILES=$HOME/dotfiles
export ZSH_PLUGINS=$DOTFILES/zsh-plugins

# Clone this theme: git@github.com:jwkicklighter/oh-my-zsh-powerline-theme.git
# Copy powerline.zsh-theme into .oh-my-zsh/themes/ (install_in_omz.sh should do this)

# Install and set terminal to 1 of these fonts: git@github.com:powerline/fonts.git
# (I use "12pt Meslo LG M Regular for Powerline" for Regular & Non-ASCII in iTerm 2)
autoload -U add-zsh-hook
ZSH_THEME="powerline"

# Custom Plugins (clone both into .oh-my-zsh/custom/plugins/[plugin name])
# git@github.com:yonchu/grunt-zsh-completion.git                Completes from Gruntfile.js
# git@github.com:zsh-users/zsh-history-substring-search.git     Searches history using typed text
# git://github.com/zsh-users/zsh-syntax-highlighting.git        Highlights terminal commands

plugins=(osx git git-flow git-extras github ruby rvm rails sublime wd bundler cap docker gem node npm bower gradle brew grunt zsh-syntax-highlighting brew zsh-history-substring-search)

source $ZSH/oh-my-zsh.sh

# User configuration

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Misc Aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias c='clear'
alias szshrc='source $HOME/.zshrc'
alias td='wd'

# Vagrant
alias vu='vagrant up'
alias vh='vagrant halt'
alias vs='vagrant suspend'

# Mac
cleanopenwith='/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain user;killall Finder;echo "Open With has been rebuilt, Finder will relaunch"'

# Grunt
alias grserve='grunt server'

# Git
alias gs='git status'
alias gf='git fetch'

# Sublime Text
alias st.='st .'

# Android
alias androiddevicemonitor='$HOME/dev/android-sdk-macosx/tools/monitor'
alias adb-net='adb tcpip 5555'
alias adb-n6='adb connect 192.168.1.44'
alias adb-usb='adb usb'

# Docker
alias b2d='boot2docker'
export DOCKER_HOST=tcp://192.168.59.103:2375

# ALL the bins!
export PATH="/usr/local/bin":$PATH
export PATH=$PATH:"/usr/local/sbin"
export PATH=$PATH:"/usr/bin"
export PATH=$PATH:"/usr/sbin"
export PATH=$PATH:"/bin"
export PATH=$PATH:"/sbin"
export PATH=$PATH:"$HOME/bin"
export PATH=$PATH:"$HOME/bin/sbt"

#Mono
export MONO_GAC_PREFIX="/usr/local"

# NPM
export PATH=$PATH:"/usr/local/share/npm/bin"

# Ruby
export PATH=$PATH:"$HOME/.rvm/bin"
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down

# Add GHC 7.10.2 to the PATH, via https://ghcformacosx.github.io/
export GHC_DOT_APP="/Applications/ghc-7.10.2.app"
if [ -d "$GHC_DOT_APP" ]; then
  export PATH="${HOME}/.local/bin:${HOME}/.cabal/bin:${GHC_DOT_APP}/Contents/bin:${PATH}"
fi
